import turtle
import random
t = turtle.Turtle()
t.speed(7)
turtle.screensize(700, 900)
turtle.bgcolor('light blue')
def createRectangle(x, y, w, h, color):
    t.begin_fill()
    t.fillcolor(color)
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.forward(w)
    t.left(90)
    t.forward(h)
    t.left(90)
    t.forward(w)
    t.left(90)
    t.forward(h)
    t.end_fill()
def createTree(x, y, w, h, color):
    t.penup()
    t.goto(x, y)
    t.pendown()
    for i in range(400, 0, -40):
        t.begin_fill()
        t.fillcolor(color)
        t.forward(h)
        t.left(90)
        t.forward(i)
        t.left(90)
        t.forward(h)
        t.left(90)
        t.forward(i)
        t.left(90)
        t.penup()
        t.goto(x + 20, y + 30)
        t.pendown()
        x = x + 20
        y = y + 30
        t.end_fill()
    t.left(230)
def createStar(x, y, size, color):
    t.begin_fill()
    t.fillcolor(color)
    t.penup()
    t.goto(x, y)
    t.pendown()
    for i in range(5):
        t.right(136)
        t.forward(size)
        t.left(64)
        t.forward(size)
    t.end_fill()
def createCircle(x, y, radius, color):
    t.begin_fill()
    t.fillcolor(color)
    t.penup()
    t.goto(x, y)
    t.circle(radius)
    t.end_fill()
    t.goto(x - 25, y)
    t.begin_fill()
    t.fillcolor('light blue')
    t.circle(radius)
    t.end_fill()
    t.penup()
createRectangle(-15, -300, 70, 85, 'brown')
createTree(-180, -185, 300, 30, 'green')
createStar(3, 100, 12.5, 'yellow')
createCircle(300, 400, 40, 'grey')

for i in range(random.randint(8, 18)):
    length = random.randint(2, 5)
    t.begin_fill()
    t.fillcolor('yellow')
    t.goto(random.randint(-300,260),random.randint(300,420))
    for i in range(5):
        t.right(136)
        t.forward(length)
        t.left(64)
        t.forward(length)
    t.end_fill()
turtle.done()
